name: bookbytes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - assets/splashscreen.png
  - assets/registration.jpg
  - assets/eula.txt
  - assets/loginpage.png
  - assets/cameralogo.png
  - assets/profile.png


